POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer Add_token_here

{
    "title": "Testi Blogi 4",
    "author": "Matti Möttönen",
    "url": "https://www.testihöpöhöpöä4.fi/"
}